<?php
define("VAR_REP_STATIC", ".THAPS_STATIC_");
define("VAR_REP_NEW", ".THAPS_NEW");

define("VAR_REP_CONST","THAPS_CONST");

define("CLASS_VISIBILITY_PUBLIC", "PUBLIC");
define("CLASS_VISIBILITY_PRIVATE", "PRIVATE");
define("CLASS_VISIBILITY_PROTECTED", "PROTECTED");
